language: generic

# require permission
sudo: required

# we need docker
services:
  - docker

before_install:
  - docker build -t monton/docker-react-s -f Dockerfile.dev .

script:
  - docker run -e CI=true monton/docker-react-s npm run test
